### ISSUE TITLE
Some REST endpoints not supported for temporal data type

### ISSUE THREAD

**Issue by RakeshArth** [sunjith/loopback-connector-neo4j-graph#7]
Loopback GET endpoint for all nodes (with no filters) of a particular label (model in loopback) throws error if any of the node has a [temporal  field](https://neo4j.com/docs/developer-manual/current/cypher/functions/temporal/) in it.  

The stack-trace is:
```javascript
TypeError: Cannot read property 'length' of undefined
    at ${workspaceRoot}\node_modules\neo4j\lib-new\GraphDatabase.js:268:45
    at ${workspaceRoot}\node_modules\neo4j\lib-new\GraphDatabase.js:286:13
    at Request._callback (${workspaceRoot}\node_modules\neo4j\lib-new\GraphDatabase.js:92:20)
    at Request.init.self.callback (${workspaceRoot}\node_modules\request\request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (${workspaceRoot}\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (${workspaceRoot}\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

Now although the error is in `neo4j` module which you have included in your dependencies, it was last updated [3 years ago](https://www.npmjs.com/package/neo4j?activeTab=versions). So I am raising the issue here.

Apparently `"resultDataContents": ["rest"]` in the JSON body of POST request to database fails when temporal fields are present. But it succeeds for  `"resultDataContents": ["row"]` or `"resultDataContents": ["graph"]` type. The whole JSON body looks something like:
```javascript
{
	"statements": [{
		"statement": "MATCH(n: Label) RETURN n",
		"parameters": {},
		"resultDataContents": [
			"rest"
		]
	}]
}
```

**Comment by sunjith** [comment]
Thank you for opening the issue.
It is high time to migrate to the [Neo4j Javascript driver](http://neo4j.com/docs/api/javascript-driver/current/) from the [Node-Neo4j driver](https://github.com/thingdom/node-neo4j). Let me know if you have the bandwidth to do that. Otherwise, I will be looking into it as and when I can find the time.

**Comment by RakeshArth** [comment]
Although I am new to Neo4j, I will give it a shot. I will issue a pull request through my personal account

**Comment by sunjith** [comment]
Excellent! Thank you.
